fix link order of HDF5 and ZLIB
The static HDF5 build depends on ZLIB symbols (inflate, compressBound, etc), so ZLIB must be linked **after** HDF5, otherwise one will see errors such as

/usr/bin/ld: build/install/lib/libhdf5.a(H5Zdeflate.c.o): in function H5Z__filter_deflate':
H5Zdeflate.c:(.text+0x8b): undefined reference to inflateInit_'
/usr/bin/ld: H5Zdeflate.c:(.text+0x145): undefined reference to inflate'
/usr/bin/ld: H5Zdeflate.c:(.text+0x166): undefined reference to inflateEnd'
/usr/bin/ld: H5Zdeflate.c:(.text+0x177): undefined reference to compressBound'
/usr/bin/ld: H5Zdeflate.c:(.text+0x1a7): undefined reference to compress2'
/usr/bin/ld: H5Zdeflate.c:(.text+0x1e4): undefined reference to inflateEnd'
/usr/bin/ld: H5Zdeflate.c:(.text+0x328): undefined reference to inflateEnd'
collect2: error: ld returned 1 exit status

during link-time. Reordering the target_link_libraries ensures the correct link order and resolves undefined reference errors.